export type HttpMethod = "GET" | "POST" | "PATCH" | "DELETE";

export interface ApiContract {
  method: HttpMethod;
  path: string;
  purpose: string;
  policyRequired: boolean;
  emittedEvents: readonly string[];
}

export const apiResponseEnvelope = {
  success: { ok: true, data: "resource | resource[] | summary" },
  failure: { ok: false, error: { code: "VALIDATION_ERROR | POLICY_DENIED | NOT_FOUND | INTERNAL_ERROR", message: "string" } }
} as const;

export const commandIdempotencyPlan = {
  header: "idempotency-key",
  status: "planned-after-mvp-command-hardening",
  rule: "Mutating endpoints will accept an idempotency key scoped by tenant, firm, actor, method, and path before external payment/document side effects are introduced."
} as const;

export const apiContracts = [
  { method: "POST", path: "/factory/blueprints/firms", purpose: "Create a tenant-scoped Firm Blueprint draft for Virtual Firm Factory provisioning", policyRequired: true, emittedEvents: ["firm_blueprint.created"] },
  { method: "POST", path: "/factory/blueprints/firms/validate", purpose: "Run deterministic Firm Blueprint and pack bundle validation", policyRequired: true, emittedEvents: ["firm_blueprint.validated", "firm_blueprint.validation_failed"] },
  { method: "POST", path: "/factory/blueprints/firms/approve", purpose: "Record explicit human approval for blueprint provisioning", policyRequired: true, emittedEvents: ["firm_blueprint.approved_for_provisioning"] },
  { method: "POST", path: "/factory/provisioning-runs", purpose: "Provision a tenant-scoped firm instance from an approved blueprint", policyRequired: true, emittedEvents: ["provisioning_run.started", "firm_instance.provisioned", "worker_binding.created"] },
  { method: "POST", path: "/factory/provisioning-runs/certify-pack-binding", purpose: "Run deterministic Practice, Service Delivery, Governance, Jurisdiction, worker, and professional authority pack certification gates before service activation", policyRequired: true, emittedEvents: ["pack.compatibility_checked", "pack.binding_certified", "pack.binding_denied", "service.activation_enabled", "service.activation_blocked"] },
  { method: "POST", path: "/factory/provisioning-runs/readiness-test", purpose: "Run factory readiness checks for a provisioned firm", policyRequired: true, emittedEvents: ["factory_readiness.checked"] },
  { method: "POST", path: "/factory/provisioning-runs/accept-handoff", purpose: "Record human acceptance of a provisioned firm for controlled local pilot handoff", policyRequired: true, emittedEvents: ["factory_handoff.accepted"] },
  { method: "GET", path: "/health", purpose: "Check API availability and persistence mode", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/contracts", purpose: "Read API contract catalogue", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/ops/readiness", purpose: "Read production-readiness, environment, persistence, release, and operational guardrail checks", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/ops/staging-package", purpose: "Read staging deployment package manifest, preflight commands, deployment steps, and rollback plan", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/ops/r4-staging-readiness", purpose: "Read Release 4 staging deployment and data protection readiness gate before private pilot invitation", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/data-protection/policy", purpose: "Read staging/pilot data protection, backup, retention, and export policy", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/data-protection/export-manifest", purpose: "Read tenant-scoped export manifest counts and integrity constraints", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/data-protection/export-package", purpose: "Export tenant/firm-scoped legally permissible business records with relationships, timestamps, provenance, policy constraints, and audit trail", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/dashboard/summary", purpose: "Read dashboard counts and latest activity", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/commercial-skill-bindings", purpose: "List bounded Sales and Accounts worker skill bindings", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/sales-pipeline-records", purpose: "List deterministic firm opportunity pipeline records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/proposal-dispatch-records", purpose: "List approval-backed human proposal dispatch records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/expense-records", purpose: "List review-controlled expense records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/receivable-follow-ups", purpose: "List review-required receivable follow-up drafts", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/accounts/cash-snapshot", purpose: "Read deterministic invoice, receipt, expense, and projected cash summary", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/commercial/skill-bindings", purpose: "Bind versioned Sales or Accounts skills to bounded worker authority", policyRequired: true, emittedEvents: ["commercial.skill_binding_activated"] },
  { method: "POST", path: "/sales/opportunities", purpose: "Create a firm-owned sales opportunity", policyRequired: true, emittedEvents: ["sales.opportunity_created"] },
  { method: "POST", path: "/sales/opportunities/update", purpose: "Apply a deterministic opportunity stage transition", policyRequired: true, emittedEvents: ["sales.opportunity_stage_changed"] },
  { method: "POST", path: "/proposals/dispatch", purpose: "Dispatch an approved proposal through a human principal command", policyRequired: true, emittedEvents: ["proposal.dispatched"] },
  { method: "POST", path: "/accounts/expenses", purpose: "Prepare an expense for human review without payment action", policyRequired: true, emittedEvents: ["accounts.expense_prepared"] },
  { method: "POST", path: "/accounts/expenses/approve", purpose: "Approve an expense without creating a payment instruction", policyRequired: true, emittedEvents: ["accounts.expense_approved"] },
  { method: "POST", path: "/accounts/receivable-follow-ups", purpose: "Draft a receivable reminder without sending", policyRequired: true, emittedEvents: ["accounts.receivable_follow_up_drafted"] },
  { method: "GET", path: "/administration-skill-bindings", purpose: "List bounded Administration Clerk skill bindings", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/correspondence-records", purpose: "List tenant-scoped correspondence records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/document-register-entries", purpose: "List controlled document register entries", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/document-revision-records", purpose: "List immutable document revision records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/administrative-deadlines", purpose: "List administrative deadlines and follow-ups", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/transmittal-drafts", purpose: "List review-required transmittal drafts", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/administration/skill-bindings", purpose: "Bind versioned role and worker skills to the Administration Clerk authority envelope", policyRequired: true, emittedEvents: ["administration.skill_binding_activated"] },
  { method: "POST", path: "/administration/correspondence", purpose: "Register incoming or draft correspondence", policyRequired: true, emittedEvents: ["administration.correspondence_registered"] },
  { method: "POST", path: "/administration/documents", purpose: "Register a document and initial immutable revision", policyRequired: true, emittedEvents: ["administration.document_registered"] },
  { method: "POST", path: "/administration/document-revisions", purpose: "Register a new revision and supersede the prior current revision", policyRequired: true, emittedEvents: ["administration.document_revision_registered"] },
  { method: "POST", path: "/administration/deadlines", purpose: "Create an attributable administrative deadline", policyRequired: true, emittedEvents: ["administration.deadline_created"] },
  { method: "POST", path: "/administration/deadlines/complete", purpose: "Complete an open administrative deadline", policyRequired: true, emittedEvents: ["administration.deadline_completed"] },
  { method: "POST", path: "/administration/transmittal-drafts", purpose: "Prepare a principal-review-required transmittal without issue", policyRequired: true, emittedEvents: ["administration.transmittal_drafted"] },
  { method: "GET", path: "/auth/context", purpose: "Read current dev-auth actor, membership, profile, and professional authority context", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/auth/staging-context", purpose: "Resolve staging-header external pilot identity to an active pilot user", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/front-desk-enquiries", purpose: "List tenant-scoped pre-client enquiries", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/client-communication-drafts", purpose: "List review-required client communication drafts", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/front-desk/enquiries", purpose: "Capture a pre-client enquiry", policyRequired: true, emittedEvents: ["front_desk.enquiry_captured"] },
  { method: "POST", path: "/front-desk/enquiries/qualify", purpose: "Record qualification after consent and conflict controls", policyRequired: true, emittedEvents: ["front_desk.enquiry_qualified"] },
  { method: "POST", path: "/front-desk/communication-drafts", purpose: "Create a review-required communication draft without sending", policyRequired: true, emittedEvents: ["front_desk.communication_drafted"] },
  { method: "POST", path: "/front-desk/enquiries/handoff", purpose: "Handoff a qualified enquiry to client intake", policyRequired: true, emittedEvents: ["front_desk.enquiry_handed_off", "client.created"] },
  { method: "GET", path: "/auth/provider/config", purpose: "Read configured external auth provider adapter status", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/auth/provider-context", purpose: "Resolve verified external provider identity to active pilot user actor context", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/tenant-admin/policy", purpose: "Read tenant and pilot admin role/action policy surface", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/support/summary", purpose: "Read tenant-scoped pilot support desk queue and access control summary", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/support/r4-incident-policy", purpose: "Read Release 4 support, triage, incident, escalation, suspension, recovery, and authority policy", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/ops/operator-metrics", purpose: "Read pilot observability, incident, support, audit, task, and commercial operator metrics", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/ops/r4-observability-audit-review", purpose: "Read Release 4 runtime trace, application log, worker action, business audit, policy decision, and evidence summaries without private chain-of-thought", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/pilot/learning-loop", purpose: "Read pilot feedback, acceptance, and improvement loop summary", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/pilot/r4-evidence-go-no-go", purpose: "Read Release 4 evidence pack readiness and go/no-go recommendation from private pilot, learning, support, observability, export, and audit evidence", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/stakeholder-review/summary", purpose: "Read pilot report pack and stakeholder review board summary", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/pilot/expansion-summary", purpose: "Read controlled pilot expansion, tenant onboarding, and release-candidate governance summary", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/pilot/r4-private-cohort-gate", purpose: "Read Release 4 private pilot cohort activation gate across R4-S1 through R4-S4 evidence, pilot users, onboarding, offboarding, and RC approval", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/tenant-usage/summary", purpose: "Read tenant usage, limit, and billing-readiness summary", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/commercial-launch/summary", purpose: "Read payment-provider preparation, subscription packaging, and commercial launch-control summary", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/operations/today", purpose: "Read SF-S6 daily operations cockpit summary for today, exceptions, workload, approvals, deadlines, pipeline, projects, and cash", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/pilot/handoff", purpose: "Record human principal acceptance of controlled local pilot handoff", policyRequired: true, emittedEvents: ["pilot_handoff.accepted"] },
  { method: "GET", path: "/payment-provider-configs", purpose: "List payment provider preparation configs", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/subscription-packages", purpose: "List subscription packages", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/commercial-launch-controls", purpose: "List commercial launch controls", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/payments/provider-configs", purpose: "Prepare payment provider configuration without live capture", policyRequired: true, emittedEvents: ["payment_provider.config_created"] },
  { method: "POST", path: "/subscriptions/packages", purpose: "Create subscription package", policyRequired: true, emittedEvents: ["subscription_package.created"] },
  { method: "POST", path: "/commercial-launch/controls", purpose: "Record commercial launch control decision", policyRequired: true, emittedEvents: ["commercial_launch.control_recorded"] },
  { method: "GET", path: "/tenant-pilot-controls", purpose: "List tenant pilot usage controls", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/tenant-usage-events", purpose: "List tenant usage events", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/billing-readiness-reviews", purpose: "List billing readiness reviews", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/tenant-pilot/controls", purpose: "Create tenant pilot usage controls", policyRequired: true, emittedEvents: ["tenant_pilot_control.created"] },
  { method: "POST", path: "/tenant-usage/events", purpose: "Record tenant usage event", policyRequired: true, emittedEvents: ["tenant_usage.recorded"] },
  { method: "POST", path: "/billing/readiness-reviews", purpose: "Record billing readiness review without live payment capture", policyRequired: true, emittedEvents: ["billing_readiness.reviewed"] },
  { method: "GET", path: "/pilot-expansion-cohorts", purpose: "List controlled pilot expansion cohorts", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/tenant-onboarding-plans", purpose: "List tenant onboarding plans", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/release-candidate-gates", purpose: "List release candidate governance gates", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/pilot/expansion-cohorts", purpose: "Create controlled pilot expansion cohort", policyRequired: true, emittedEvents: ["pilot_expansion.cohort_created"] },
  { method: "POST", path: "/pilot/expansion-cohorts/update", purpose: "Update controlled pilot expansion cohort", policyRequired: true, emittedEvents: ["pilot_expansion.cohort_updated"] },
  { method: "POST", path: "/pilot/private-cohort/activate", purpose: "Activate a private pilot cohort only after R4-S1 through R4-S4 evidence gates, onboarding, offboarding, and RC approval pass", policyRequired: true, emittedEvents: ["pilot_private_cohort.activated"] },
  { method: "POST", path: "/tenant-onboarding/plans", purpose: "Create tenant onboarding plan for controlled expansion", policyRequired: true, emittedEvents: ["tenant_onboarding.plan_created"] },
  { method: "POST", path: "/tenant-onboarding/plans/update", purpose: "Update or complete tenant onboarding plan", policyRequired: true, emittedEvents: ["tenant_onboarding.plan_updated"] },
  { method: "POST", path: "/release-candidate/gates", purpose: "Record release candidate governance gate", policyRequired: true, emittedEvents: ["release_candidate.gate_recorded"] },
  { method: "GET", path: "/pilot-report-packs", purpose: "List pilot report packs", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/stakeholder-review-boards", purpose: "List stakeholder review boards", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/stakeholder-review-decisions", purpose: "List stakeholder review decisions", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/pilot/report-packs", purpose: "Generate pilot reporting and export pack", policyRequired: true, emittedEvents: ["pilot_report_pack.generated"] },
  { method: "POST", path: "/stakeholder-review/boards", purpose: "Open stakeholder review board", policyRequired: true, emittedEvents: ["stakeholder_review_board.opened"] },
  { method: "POST", path: "/stakeholder-review/decisions", purpose: "Record stakeholder review decision", policyRequired: true, emittedEvents: ["stakeholder_review.decision_recorded"] },
  { method: "GET", path: "/pilot-feedback", purpose: "List pilot feedback records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/pilot-acceptance-reviews", purpose: "List pilot acceptance reviews", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/pilot-improvement-items", purpose: "List pilot improvement backlog items", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/pilot/feedback", purpose: "Submit structured pilot feedback", policyRequired: true, emittedEvents: ["pilot_feedback.submitted"] },
  { method: "POST", path: "/pilot/acceptance-reviews", purpose: "Record pilot acceptance criteria review", policyRequired: true, emittedEvents: ["pilot_acceptance.reviewed"] },
  { method: "POST", path: "/pilot/improvement-items", purpose: "Create product improvement item from pilot learning", policyRequired: true, emittedEvents: ["pilot_improvement.created"] },
  { method: "POST", path: "/pilot/improvement-items/update", purpose: "Update or close pilot improvement item", policyRequired: true, emittedEvents: ["pilot_improvement.updated"] },
  { method: "GET", path: "/pilot-incidents", purpose: "List pilot incidents", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/ops/incidents", purpose: "Open a pilot operational incident", policyRequired: true, emittedEvents: ["pilot_incident.opened"] },
  { method: "POST", path: "/ops/incidents/update", purpose: "Update or resolve a pilot operational incident", policyRequired: true, emittedEvents: ["pilot_incident.updated"] },
  { method: "GET", path: "/support-cases", purpose: "List support cases", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/support/cases", purpose: "Open a pilot support case", policyRequired: true, emittedEvents: ["support_case.opened"] },
  { method: "POST", path: "/support/cases/update", purpose: "Update or close a pilot support case", policyRequired: true, emittedEvents: ["support_case.updated"] },
  { method: "POST", path: "/pilot/users/revoke", purpose: "Revoke pilot user access", policyRequired: true, emittedEvents: ["pilot_user.revoked"] },
  { method: "POST", path: "/pilot/users/suspend", purpose: "Suspend pilot user access without deleting the auditable identity record", policyRequired: true, emittedEvents: ["pilot_user.suspended"] },
  { method: "GET", path: "/service-packs/formwork", purpose: "Read the Formwork MVP service pack metadata", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/pilot/formwork", purpose: "Read Formwork pilot package scope, onboarding checklist, and pilot acceptance criteria", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/pilot-users", purpose: "List pilot users for controlled external trial management", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/pilot/users/invite", purpose: "Invite a pilot user into a tenant or firm pilot", policyRequired: true, emittedEvents: ["pilot_user.invited"] },
  { method: "POST", path: "/pilot/users/activate", purpose: "Activate a pilot user after external identity verification", policyRequired: true, emittedEvents: ["pilot_user.activated"] },
  { method: "GET", path: "/service-packs", purpose: "List service pack records", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/service-packs/{id}", purpose: "Read service pack detail", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/service-skus", purpose: "List service SKU records", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/service-skus/{id}", purpose: "Read service SKU detail", policyRequired: false, emittedEvents: [] },
  { method: "GET", path: "/worker-templates", purpose: "List AI worker templates", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/worker-instances", purpose: "List firm AI worker instances", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/task-outputs", purpose: "List AI worker task outputs", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/tool-invocations", purpose: "List AI worker tool invocations", policyRequired: true, emittedEvents: [] },  { method: "GET", path: "/marketplace-listings", purpose: "List private trusted-network marketplace listings", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/capacity-offers", purpose: "List trusted-network capacity offers", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/collaboration-requests", purpose: "List firm collaboration requests", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/observatory-snapshots", purpose: "List privacy-safe network observatory snapshots", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/marketplace/governance-lock", purpose: "Read ME-S1 marketplace governance policy lock and implementation boundaries", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/marketplace/qualified-directory-summary", purpose: "Read ME-S2 qualified private directory readiness checks", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/marketplace/directory-publications", purpose: "Publish controlled private qualified directory listing after human approval and verified qualification evidence", policyRequired: true, emittedEvents: ["marketplace.listing_published"] },
  { method: "POST", path: "/marketplace/directory-publications/suspend", purpose: "Suspend controlled qualified directory publication", policyRequired: true, emittedEvents: ["marketplace.directory_publication_suspended"] },
  { method: "POST", path: "/marketplace/directory-publications/revoke", purpose: "Revoke controlled qualified directory publication", policyRequired: true, emittedEvents: ["marketplace.directory_publication_revoked"] },
  { method: "GET", path: "/marketplace/private-directory-governance-summary", purpose: "Read ME-S3 private directory review board, enquiry, renewal, audit, and boundary readiness", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/marketplace/directory-review-board/decisions", purpose: "Record controlled private directory review board decision without granting authority or marketplace award", policyRequired: true, emittedEvents: ["marketplace.directory_review_board_decision_recorded"] },
  { method: "POST", path: "/marketplace/private-directory/enquiries", purpose: "Record manual private enquiry against a qualified directory listing without live matching or ranking", policyRequired: true, emittedEvents: ["marketplace.private_directory_enquiry_recorded"] },
  { method: "POST", path: "/marketplace/private-directory/enquiries/request-collaboration", purpose: "Progress private directory enquiry to manual collaboration request without award or matching", policyRequired: true, emittedEvents: ["marketplace.directory_enquiry_collaboration_requested"] },
  { method: "POST", path: "/marketplace/qualification-renewal-reviews", purpose: "Record qualification renewal or expiry review and suspend private listing when required", policyRequired: true, emittedEvents: ["marketplace.qualification_renewal_review_recorded"] },
  { method: "POST", path: "/marketplace/listings", purpose: "Publish private trusted-network service listing", policyRequired: true, emittedEvents: ["marketplace.listing_published"] },
  { method: "POST", path: "/capacity/offers", purpose: "Create capacity offer for trusted network", policyRequired: true, emittedEvents: ["capacity_offer.created"] },
  { method: "POST", path: "/collaboration/requests", purpose: "Request controlled firm collaboration through data-room policy", policyRequired: true, emittedEvents: ["collaboration.requested"] },
  { method: "POST", path: "/observatory/snapshots", purpose: "Create aggregated privacy-safe network observatory snapshot", policyRequired: true, emittedEvents: ["observatory.snapshot_created"] },
  { method: "POST", path: "/worker-instances", purpose: "Provision bounded AI worker instance", policyRequired: true, emittedEvents: ["worker_instance.provisioned"] },
  { method: "POST", path: "/worker-instances/activate", purpose: "Activate provisioned AI worker instance", policyRequired: true, emittedEvents: ["worker_instance.activated"] },
  { method: "POST", path: "/runtime/tasks/assign-ai", purpose: "Assign delivery task to active AI worker", policyRequired: true, emittedEvents: ["task.assigned_to_worker"] },
  { method: "POST", path: "/runtime/tool-invocations", purpose: "Request allowed AI worker tool invocation", policyRequired: true, emittedEvents: ["tool.invocation_requested"] },
  { method: "POST", path: "/runtime/tasks/output", purpose: "Capture reviewable AI worker output", policyRequired: true, emittedEvents: ["task.output_produced"] },
  { method: "GET", path: "/tenants", purpose: "List tenants", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/tenants/{id}", purpose: "Read tenant detail", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/tenants", purpose: "Create tenant", policyRequired: true, emittedEvents: ["tenant.created"] },
  { method: "GET", path: "/firms", purpose: "List firms", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/firms/{id}", purpose: "Read firm detail", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/firm-memberships", purpose: "List firm memberships", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/professional-profiles", purpose: "List professional profiles", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/professional-authorities", purpose: "List professional authorities", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/firms", purpose: "Create Firm draft/application", policyRequired: true, emittedEvents: ["firm.application_submitted"] },
  { method: "GET", path: "/clients", purpose: "List clients", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/clients/{id}", purpose: "Read client detail", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/clients", purpose: "Create client", policyRequired: true, emittedEvents: ["client.created"] },
  { method: "GET", path: "/intake-sessions", purpose: "List intake sessions", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/intake-sessions/{id}", purpose: "Read intake session detail", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/intake-sessions", purpose: "Create intake session", policyRequired: true, emittedEvents: ["lead.created", "intake.completed"] },
  { method: "GET", path: "/proposals", purpose: "List proposals", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/proposals/{id}", purpose: "Read proposal detail", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/proposals", purpose: "Create proposal draft", policyRequired: true, emittedEvents: ["proposal.created"] },
  { method: "POST", path: "/proposals/approve", purpose: "Approve proposal", policyRequired: true, emittedEvents: ["approval.granted", "proposal.approved"] },
  { method: "POST", path: "/proposals/accept", purpose: "Accept proposal and open delivery project", policyRequired: true, emittedEvents: ["engagement.created", "project.opened", "task.created"] },
  { method: "GET", path: "/projects", purpose: "List projects", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/projects/{id}", purpose: "Read project detail", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/work-packages", purpose: "List work packages", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/tasks", purpose: "List delivery tasks", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/tasks/start", purpose: "Start delivery task", policyRequired: true, emittedEvents: ["task.started"] },
  { method: "POST", path: "/tasks/complete", purpose: "Complete delivery task", policyRequired: true, emittedEvents: ["task.completed"] },
  { method: "GET", path: "/documents", purpose: "List delivery documents", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/document-versions", purpose: "List delivery document versions", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/deliverables/draft", purpose: "Create deliverable draft document version", policyRequired: true, emittedEvents: ["document.version_created"] },
  { method: "POST", path: "/deliverables/review", purpose: "Review and approve deliverable version against evidence bundle", policyRequired: true, emittedEvents: ["deliverable.review_approved"] },
  { method: "POST", path: "/deliverables/issue", purpose: "Issue approved deliverable version", policyRequired: true, emittedEvents: ["deliverable.issued"] },
  { method: "GET", path: "/invoices", purpose: "List invoices", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/invoices/{id}", purpose: "Read invoice detail", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/invoices", purpose: "Create invoice", policyRequired: true, emittedEvents: ["invoice.created"] },
  { method: "POST", path: "/invoices/issue", purpose: "Issue invoice after delivery gate", policyRequired: true, emittedEvents: ["invoice.issued"] },
  { method: "GET", path: "/payment-statuses", purpose: "List payment status records", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/payments/record", purpose: "Record payment status against issued invoice", policyRequired: true, emittedEvents: ["payment.recorded"] },
  { method: "POST", path: "/evidence-bundles", purpose: "Create evidence bundle", policyRequired: true, emittedEvents: ["evidence_bundle.created"] },
  { method: "GET", path: "/audit-events", purpose: "List audit events", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/event-log", purpose: "List canonical event log", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/policy/evaluate", purpose: "Evaluate policy decision", policyRequired: false, emittedEvents: ["policy.evaluated"] },
  { method: "GET", path: "/mvp/store", purpose: "Compatibility full-store read for local development fallback", policyRequired: false, emittedEvents: [] },
  { method: "POST", path: "/mvp/demo-loop", purpose: "Run full local MVP workflow demo", policyRequired: false, emittedEvents: ["tenant.created", "firm.application_submitted", "client.created", "intake.completed", "proposal.created", "approval.granted", "project.opened", "evidence_bundle.created", "invoice.created"] },
  { method: "GET", path: "/technical-skill-bindings", purpose: "List bounded technical skill bindings", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/drawing-review-records", purpose: "List drawing revision checks", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/calculation-input-sets", purpose: "List deterministic Formwork input validations", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/technical-qa-findings", purpose: "List technical QA findings", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/delivery-package-records", purpose: "List delivery package readiness records", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/technical/skill-bindings", purpose: "Bind bounded technical support skills", policyRequired: true, emittedEvents: ["technical.skill_binding_activated"] },
  { method: "POST", path: "/technical/drawing-reviews", purpose: "Check drawing revisions for professional review", policyRequired: true, emittedEvents: ["technical.drawing_revisions_checked"] },
  { method: "POST", path: "/technical/calculation-input-sets", purpose: "Validate Formwork inputs without engineering conclusions", policyRequired: true, emittedEvents: ["technical.calculation_inputs_validated", "technical.calculation_inputs_invalid"] },
  { method: "POST", path: "/technical/qa-findings", purpose: "Raise technical QA finding", policyRequired: true, emittedEvents: ["technical.qa_finding_raised"] },
  { method: "POST", path: "/technical/qa-findings/resolve", purpose: "Human principal resolves QA finding", policyRequired: true, emittedEvents: ["technical.qa_finding_resolved"] },
  { method: "POST", path: "/technical/delivery-packages", purpose: "Assemble blocked or review-ready technical package", policyRequired: true, emittedEvents: ["technical.delivery_package_blocked", "technical.delivery_package_ready_for_principal_review"] },
  { method: "GET", path: "/network-professional-profiles", purpose: "List trusted-network professional profiles without granting professional authority", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network-firm-profiles", purpose: "List trusted-network firm profiles", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network-capabilities", purpose: "List qualification-required trusted-network capabilities", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network-credentials", purpose: "List trusted-network credential evidence records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network-trust-signals", purpose: "List trust signals that cannot substitute for credentials", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network/r5-profile-summary", purpose: "Read R5-S1 trusted network readiness checks", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/network/professional-profiles", purpose: "Create trusted-network professional profile without granting professional authority", policyRequired: true, emittedEvents: ["network.professional_profile_created"] },
  { method: "POST", path: "/network/firm-profiles", purpose: "Create trusted-network firm profile", policyRequired: true, emittedEvents: ["network.firm_profile_created"] },
  { method: "POST", path: "/network/capabilities", purpose: "Create qualification-required trusted-network capability", policyRequired: true, emittedEvents: ["network.capability_created"] },
  { method: "POST", path: "/network/credentials", purpose: "Record trusted-network credential evidence without authority grant", policyRequired: true, emittedEvents: ["network.credential_recorded"] },
  { method: "POST", path: "/network/trust-signals", purpose: "Record trusted-network trust signal that cannot replace credential verification", policyRequired: true, emittedEvents: ["network.trust_signal_recorded"] },
  { method: "GET", path: "/network-conflict-checks", purpose: "List trusted-network conflict checks", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network-qualification-gates", purpose: "List qualification gates for trusted specialist invitation", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/specialist-invitations", purpose: "List specialist invitations and denied invitation evidence", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network/r5-qualification-summary", purpose: "Read R5-S2 qualification and conflict gate readiness checks", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/network/conflict-checks", purpose: "Record conflict screening result before trusted specialist invitation", policyRequired: true, emittedEvents: ["network.conflict_check_recorded"] },
  { method: "POST", path: "/network/qualification-gates", purpose: "Evaluate credential, jurisdiction, insurance, conflict, capacity, and policy gates before invitation", policyRequired: true, emittedEvents: ["network.qualification_gate_passed", "network.qualification_gate_denied"] },
  { method: "POST", path: "/network/specialist-invitations", purpose: "Prepare specialist invitation only when qualification gate has passed", policyRequired: true, emittedEvents: ["network.specialist_invitation_ready", "network.specialist_invitation_denied"] },
  { method: "GET", path: "/collaboration-workspaces", purpose: "List scoped trusted collaboration workspaces", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/collaboration-workspace-participants", purpose: "List scoped collaboration workspace participant grants and revocations", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/collaboration-workspace-evidence", purpose: "List workspace-scoped collaboration evidence references", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network/r5-collaboration-workspace-summary", purpose: "Read R5-S3 collaboration workspace readiness checks", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/network/collaboration-workspaces", purpose: "Open scoped trusted collaboration workspace from ready specialist invitation", policyRequired: true, emittedEvents: ["network.collaboration_workspace_opened"] },
  { method: "POST", path: "/network/collaboration-workspaces/participants", purpose: "Grant scoped collaboration workspace participant access", policyRequired: true, emittedEvents: ["network.collaboration_participant_granted"] },
  { method: "POST", path: "/network/collaboration-workspaces/participants/revoke", purpose: "Revoke scoped collaboration workspace participant access", policyRequired: true, emittedEvents: ["network.collaboration_participant_revoked"] },
  { method: "POST", path: "/network/collaboration-workspaces/evidence", purpose: "Add workspace-scoped collaboration evidence reference", policyRequired: true, emittedEvents: ["network.collaboration_evidence_added"] },
  { method: "GET", path: "/responsibility-matrices", purpose: "List trusted collaboration responsibility and approval matrices", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network/r5-responsibility-matrix-summary", purpose: "Read R5-S4 responsibility and approval matrix readiness checks", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/network/responsibility-matrices", purpose: "Record explicit accountable firm, responsible professional, reviewer, approver, and permitted worker actions", policyRequired: true, emittedEvents: ["network.responsibility_matrix_recorded"] },
  { method: "GET", path: "/specialist-assignments", purpose: "List trusted specialist assignment lifecycle records", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network/r5-assignment-delivery-summary", purpose: "Read R5-S5 specialist assignment and delivery loop readiness checks", policyRequired: true, emittedEvents: [] },
  { method: "GET", path: "/network/r5-network-evidence-go-no-go", purpose: "Read R5-S6 network evidence pack and go/no-go recommendation", policyRequired: true, emittedEvents: [] },
  { method: "POST", path: "/network/specialist-assignments", purpose: "Request trusted specialist assignment under an active responsibility matrix", policyRequired: true, emittedEvents: ["network.specialist_assignment_requested"] },
  { method: "POST", path: "/network/specialist-assignments/accept", purpose: "Responsible professional accepts specialist assignment", policyRequired: true, emittedEvents: ["network.specialist_assignment_accepted"] },
  { method: "POST", path: "/network/specialist-assignments/start", purpose: "Responsible professional starts specialist assignment work", policyRequired: true, emittedEvents: ["network.specialist_assignment_started"] },
  { method: "POST", path: "/network/specialist-assignments/deliver", purpose: "Responsible professional delivers assignment evidence", policyRequired: true, emittedEvents: ["network.specialist_assignment_delivered"] },
  { method: "POST", path: "/network/specialist-assignments/review", purpose: "Recorded reviewer reviews specialist delivery", policyRequired: true, emittedEvents: ["network.specialist_assignment_reviewed"] },
  { method: "POST", path: "/network/specialist-assignments/approve", purpose: "Recorded approver approves specialist delivery", policyRequired: true, emittedEvents: ["network.specialist_assignment_approved"] },
  { method: "POST", path: "/network/specialist-assignments/close", purpose: "Recorded approver closes approved specialist delivery", policyRequired: true, emittedEvents: ["network.specialist_assignment_closed"] }] as const satisfies readonly ApiContract[];

